version: '3'

services:
  b4-app:
    image: node:10.18.1-jessie
    restart: always
    volumes:
      - "../b4-app:/app/b4-app"
      - "../data:/app/data"
      - "../databases:/app/databases"
      - "../esclu:/app/esclu"
      - "./b4-entrypoint.sh:/app/b4-entrypoint.sh"
    ports:
      - "60900:60900"
    environment:
      NODE_ENV: production
    working_dir: /app
    command: ./b4-entrypoint.sh
    networks:
      - b4
  
  es:
    image: elasticsearch:7.5.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - b4

  redis:
    image: redis:5.0.7-buster
    restart: always
    ports:
      - "6379:6379"
    # https://kuzunoha-ne.hateblo.jp/entry/2019/02/22/203300
    command: ["redis-server", "--requirepass", "thisissecret"]
    networks:
      - b4

networks:
  b4:
