version: '3'

services:
  b4-backend:
    image: node:10.18.1-jessie
    restart: always
    volumes:
      - "../data:/data"
      - "../b4:/app"
    ports:
      - "60702:60702"
    working_dir: /app
    command: npm start
    networks:
      - b4

  b4-app:
    image: node:10.18.1-jessie
    restart: always
    volumes:
      - "../b4-app:/app"
    ports:
      - "60900:60900"
    working_dir: /app
    command: npm start
    networks:
      - b4
  
  es:
    image: elasticsearch:7.5.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - b4

networks:
  b4:
